### ISSUE TITLE
How to handle MODD2 dataset?

### ISSUE THREAD

**Issue by amdslgl** [bborja/wasr_network#4]
hello sir,I am so grateful for your work，but I have a question to ask. MODD2 dataset is labeled by matlab, but I do not know how to convert it as train_water_deformed.txt. if you can tell me something about it , these will be better.

**Comment by bborja** [comment]
Do you want to use images from the MODD2 dataset for inference? If so, then simply create the text file where each line is composed of a pair:
`path_to_image path_to_corresponding_imu`

If you want to use the MODD2 images for training, then I have to unfortunately notify you that this is not possible, as those images are not pixel-wise annotated.
